### ISSUE TITLE
something error

### ISSUE THREAD

**Issue by abe520** [dreknix/docker-compose-pxe#1]
openwrt dnsmasq
```
enable-tftp
dhcp-match=set:ipxe,175
dhcp-match=set:bios,60,PXEClient:Arch:00000
dhcp-boot=tag:bios,undionly.kpxe,,192.168.12.51
dhcp-match=set:efi32,60,PXEClient:Arch:00006
dhcp-boot=tag:efi32,ipxe.efi,,192.168.12.51
dhcp-match=set:efi64,60,PXEClient:Arch:00007
dhcp-boot=tag:efi64,ipxe.efi,,192.168.12.51
dhcp-boot=tag:ipxe,boot.ipxe,,192.168.12.51
```
docker compose
```
  tftpd:
    image: dreknix/pxe-tftpd:latest
    container_name: pxe-tftpd
    volumes:
      - pxe-tftpboot:/tftpboot
    network_mode: host
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
      - SYS_CHROOT
      - NET_BIND_SERVICE

  httpd:
    image: dreknix/pxe-httpd:latest
    container_name: pxe-httpd

    volumes:
      - pxe-www:/www
      - $DOCKERDIR/pxe/config_local.json:/config_local.json
    ports:
      - 8069:8069
    cap_drop:
      - ALL

volumes:
  pxe-tftpboot:
    external: true
  pxe-www:
    external: true
```
config_local.json pxe.my.app=192.168.12.51
```
{
  "PXE_HOSTNAME": "pxe.my.app"
}
```
boot error
![Snipaste_2023-05-17_05-43-16](https://github.com/dreknix/docker-compose-pxe/assets/9929511/62bd4119-4591-41cb-84f8-190bb075826a)
